#! /bin/sh

cleanup()
{
    echo "Cleaning the distribution..."
    make distclean
    echo

    echo "Cleaning old configuration..."
    rm -f config/*
    rm -f Makefile.in
    rm -f aclocal.m4
    rm -rf autom4te.cache
    rm -f config.h.in
    rm -f config.log
    rm -f configure
    rm -f src/Makefile.in
    echo
}

regen_config()
{
    echo "Generating new configuration..."
    aclocal --force
    autoheader --force
    automake --gnu --add-missing --copy --force-missing
    autoconf
    echo
}

if test "$1" = clean; then
    cleanup
    exit 0
elif test "$1" = configure; then
    cleanup
    regen_config
    ./configure
    exit 0
elif test "$1" = build; then
    cleanup
    regen_config
    ./configure
    make
    exit 0
fi

cleanup
regen_config
